// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* leftRearMotor;
	SpeedController* leftFrontMotor;
	SpeedController* rightRearMotor;
	SpeedController* rightFrontMotor;
	RobotDrive* robotDrive41;
	Gyro* plyBotDriveGyro;
	Encoder* leftFrontMotorQuadratureEncoder;
	Encoder* leftRearMotorQuadratureEncoder;
	Encoder* rightFrontMotorQuadratureEncoder;
	Encoder* rightRearMotorQuadratureEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	const float WHEEL_DIAMETER_IN_INCHES = 6;
	const float WHEEL_CIRCUMFERENCE_IN_INCHES = WHEEL_DIAMETER_IN_INCHES * 3.14;
	const float WHEEL_CIRCUMFERENCE_IN_FEET = WHEEL_CIRCUMFERENCE_IN_INCHES / 12;

	DriveTrain();
	void InitDefaultCommand();

	// mechanum cartesian drive, parameters: x, y and rotation angle
	void drive(float, float, float);
};

#endif
