// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* speedController1;
	SpeedController* speedController2;
	SpeedController* speedController3;
	SpeedController* speedController4;
	RobotDrive* robotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	const float WHEELDIAMETER_ININCHES = 6; //inches
	const float WHEELCIRCUMFERENCE_ININCHES = WHEELDIAMETER_ININCHES * 3.14;	//no pi key
	const float WHEELCIRCUMFERENCE_INFEET = WHEELCIRCUMFERENCE_ININCHES / 12;
	const float WHEELROTATION_PERFOOT = 1/WHEELCIRCUMFERENCE_INFEET;	//amount of rotations per foot
	const int  ENCODERTICKS_PERREVOLUTION = 220;
	DriveTrain();
	void InitDefaultCommand();

	//signature, this will passes x, y, and the rotation angle
	void drive(float, float, float);
};

#endif
