// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Drive.h"

Drive::Drive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}


// Called just before this Command runs the first time
void Drive::Initialize() {
	
}

float delinearize (float input, float alpha)
{
	input = (alpha * input * input * input) + (( 1 - alpha) * input);
	return input;
}

// Called repeatedly when this Command is scheduled to run
void Drive::Execute() {
	float x = Robot::oi->getJoystick1()->GetX();
	float y = Robot::oi->getJoystick1()->GetY();
	float z = Robot::oi->getJoystick1()->GetZ();
	// Robot::driveTrain->drive(x,y,z);

	float alpha = Robot::oi -> getJoystick1() -> GetThrottle();

	x = delinearize(x, alpha);
	y = delinearize (y, alpha);
	z = delinearize (z, alpha);

	Robot:: driveTrain -> drive (x, y, z);
}



float deadband (float input, float db)
{
	if (input > db) db = db * 1;
	else if (input < -db)  db = input;
	else db = 0;
	return db;
}

// Make this return true when this Command no longer needs to run execute()
bool Drive::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void Drive::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Drive::Interrupted() {

}
