// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveTwoFeet.h"

DriveTwoFeet::DriveTwoFeet() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void DriveTwoFeet::Initialize() {
	Robot::driveTrain->leftFrontMotorQuadratureEncoder->Reset()
	
}

// Called repeatedly when this Command is scheduled to run
void DriveTwoFeet::Execute() {
	Robot::driveTrain->drive(0, .25, 0);
	
}

// Make this return true when this Command no longer needs to run execute()
bool DriveTwoFeet::IsFinished() {
	int ticks = Robot::driveTrain->leftFrontMotorQuadratureEncoder->Get();
	int ticks_needed = Robot::driveTrain->WHEEL_ROTATION_PER_FOOT * Robot::driveTrain->ENCODER_TICKS_PER_REVOLUTION * 2;
	if(ticks >= ticks_needed)
		{
		return true;

	}
	return false;
}

// Called once after isFinished returns true
void DriveTwoFeet::End() {
	Robot::driveTrain-> drive (0, 0, 0);
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveTwoFeet::Interrupted() {
End();

}
