// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "TurnNDegrees.h"

TurnNDegrees::TurnNDegrees(float n) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);

	ndegrees = n;
	startposition = 0.0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void TurnNDegrees::Initialize() {
	startposition = Robot::driveTrain->driveGyro->GetAngle();
	
}

// Called repeatedly when this Command is scheduled to run
void TurnNDegrees::Execute() {
	Robot::driveTrain->drive(0, 0, .25 * (ndegrees > 0 ? 1 : -1));
			//Turn at quarter speed right
}

// Make this return true when this Command no longer needs to run execute()
bool TurnNDegrees::IsFinished() {
	int currentAngle = Robot::driveTrain->driveGyro->GetAngle();
			//the current position

		if (ndegrees > 0 && currentAngle >= (startposition+ndegrees))
			return true;
		else if (ndegrees < 0 && currentAngle <= (startposition+ndegrees))
			return true;
		else if (ndegrees == 0)
			return true;
		else
			return false;
}

// Called once after isFinished returns true
void TurnNDegrees::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnNDegrees::Interrupted() {

}
