// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainLeftFrontMotor = NULL;
SpeedController* RobotMap::driveTrainLeftRearMotor = NULL;
SpeedController* RobotMap::driveTrainRightFrontMotor = NULL;
SpeedController* RobotMap::driveTrainRightRearMotor = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive41 = NULL;
Gyro* RobotMap::driveTrainDriveGyro = NULL;
Encoder* RobotMap::driveTrainQuadratureEncoderLeftFront = NULL;
Encoder* RobotMap::driveTrainQuadratureEncoderLeftRear = NULL;
Encoder* RobotMap::driveTrainQuadratureEncoderRightFront = NULL;
Encoder* RobotMap::driveTrainQuadratureEncoderRightRear = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainLeftFrontMotor = new TalonSRX(0);
	lw->AddActuator("DriveTrain", "LeftFrontMotor", (TalonSRX*) driveTrainLeftFrontMotor);
	
	driveTrainLeftRearMotor = new TalonSRX(1);
	lw->AddActuator("DriveTrain", "LeftRearMotor", (TalonSRX*) driveTrainLeftRearMotor);
	
	driveTrainRightFrontMotor = new TalonSRX(2);
	lw->AddActuator("DriveTrain", "RightFrontMotor", (TalonSRX*) driveTrainRightFrontMotor);
	
	driveTrainRightRearMotor = new TalonSRX(3);
	lw->AddActuator("DriveTrain", "RightRearMotor", (TalonSRX*) driveTrainRightRearMotor);
	
	driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRightRearMotor);
	
	driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.5);
        driveTrainRobotDrive41->SetMaxOutput(1.0);

        driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
	driveTrainDriveGyro = new Gyro(0);
	lw->AddSensor("DriveTrain", "DriveGyro", driveTrainDriveGyro);
	driveTrainDriveGyro->SetSensitivity(0.007);
	driveTrainQuadratureEncoderLeftFront = new Encoder(0, 1, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "QuadratureEncoderLeftFront", driveTrainQuadratureEncoderLeftFront);
	driveTrainQuadratureEncoderLeftFront->SetDistancePerPulse(1.0);
        driveTrainQuadratureEncoderLeftFront->SetPIDSourceParameter(Encoder::kRate);
	driveTrainQuadratureEncoderLeftRear = new Encoder(2, 3, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "QuadratureEncoderLeftRear", driveTrainQuadratureEncoderLeftRear);
	driveTrainQuadratureEncoderLeftRear->SetDistancePerPulse(1.0);
        driveTrainQuadratureEncoderLeftRear->SetPIDSourceParameter(Encoder::kRate);
	driveTrainQuadratureEncoderRightFront = new Encoder(4, 5, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "QuadratureEncoderRightFront", driveTrainQuadratureEncoderRightFront);
	driveTrainQuadratureEncoderRightFront->SetDistancePerPulse(1.0);
        driveTrainQuadratureEncoderRightFront->SetPIDSourceParameter(Encoder::kRate);
	driveTrainQuadratureEncoderRightRear = new Encoder(6, 7, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "QuadratureEncoderRightRear", driveTrainQuadratureEncoderRightRear);
	driveTrainQuadratureEncoderRightRear->SetDistancePerPulse(1.0);
        driveTrainQuadratureEncoderRightRear->SetPIDSourceParameter(Encoder::kRate);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
