// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainLeftFrontMtor = NULL;
SpeedController* RobotMap::driveTrainLeftRearMotor = NULL;
SpeedController* RobotMap::driveTrainRightFrontMotor = NULL;
SpeedController* RobotMap::driveTrainRightRearMotor = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive41 = NULL;
Gyro* RobotMap::driveTrainPlyBotDriveGyro = NULL;
Encoder* RobotMap::driveTrainLeftFrontMotorQuadratureEncoder = NULL;
Encoder* RobotMap::driveTrainLeftRearMotorQuadratureEncoder = NULL;
Encoder* RobotMap::driveTrainRightFrontMotorQuadratureEncoder = NULL;
Encoder* RobotMap::driveTrainRightRearMotorQuadratureEncoder = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainLeftFrontMtor = new TalonSRX(0);
	lw->AddActuator("DriveTrain", "LeftFrontMtor", (TalonSRX*) driveTrainLeftFrontMtor);
	
	driveTrainLeftRearMotor = new TalonSRX(1);
	lw->AddActuator("DriveTrain", "LeftRearMotor", (TalonSRX*) driveTrainLeftRearMotor);
	
	driveTrainRightFrontMotor = new TalonSRX(2);
	lw->AddActuator("DriveTrain", "RightFrontMotor", (TalonSRX*) driveTrainRightFrontMotor);
	
	driveTrainRightRearMotor = new TalonSRX(3);
	lw->AddActuator("DriveTrain", "RightRearMotor", (TalonSRX*) driveTrainRightRearMotor);
	
	driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFrontMtor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRightRearMotor);
	
	driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.5);
        driveTrainRobotDrive41->SetMaxOutput(1.0);

        driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
	driveTrainPlyBotDriveGyro = new Gyro(0);
	lw->AddSensor("DriveTrain", "PlyBotDriveGyro", driveTrainPlyBotDriveGyro);
	driveTrainPlyBotDriveGyro->SetSensitivity(0.007);
	driveTrainLeftFrontMotorQuadratureEncoder = new Encoder(0, 1, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "LeftFrontMotorQuadratureEncoder", driveTrainLeftFrontMotorQuadratureEncoder);
	driveTrainLeftFrontMotorQuadratureEncoder->SetDistancePerPulse(1.0);
        driveTrainLeftFrontMotorQuadratureEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainLeftRearMotorQuadratureEncoder = new Encoder(2, 3, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "LeftRearMotorQuadratureEncoder", driveTrainLeftRearMotorQuadratureEncoder);
	driveTrainLeftRearMotorQuadratureEncoder->SetDistancePerPulse(1.0);
        driveTrainLeftRearMotorQuadratureEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainRightFrontMotorQuadratureEncoder = new Encoder(4, 5, true, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightFrontMotorQuadratureEncoder", driveTrainRightFrontMotorQuadratureEncoder);
	driveTrainRightFrontMotorQuadratureEncoder->SetDistancePerPulse(1.0);
        driveTrainRightFrontMotorQuadratureEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainRightRearMotorQuadratureEncoder = new Encoder(8, 9, true, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightRearMotorQuadratureEncoder", driveTrainRightRearMotorQuadratureEncoder);
	driveTrainRightRearMotorQuadratureEncoder->SetDistancePerPulse(1.0);
        driveTrainRightRearMotorQuadratureEncoder->SetPIDSourceParameter(Encoder::kRate);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
