// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainLeftFrontMotor = NULL;
SpeedController* RobotMap::driveTrainLeftRearMotor = NULL;
SpeedController* RobotMap::driveTrainRightFrontMotor = NULL;
SpeedController* RobotMap::driveTrainRightRearMotor = NULL;
<<<<<<< HEAD
RobotDrive* RobotMap::driveTrainMotorController = NULL;
=======
RobotDrive* RobotMap::driveTrainRobotDrive4Motors = NULL;
>>>>>>> origin/bailey
Encoder* RobotMap::driveTrainLeftFrontEncoder = NULL;
Encoder* RobotMap::driveTrainLeftRearEncoder = NULL;
Encoder* RobotMap::driveTrainRightFrontEncoder = NULL;
Encoder* RobotMap::driveTrainRightRearEncoder = NULL;
<<<<<<< HEAD
Gyro* RobotMap::driveTrainMainGyro = NULL;
=======
Gyro* RobotMap::driveTrainDriveGyro = NULL;
>>>>>>> origin/bailey

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainLeftFrontMotor = new TalonSRX(0);
	lw->AddActuator("DriveTrain", "LeftFrontMotor", (TalonSRX*) driveTrainLeftFrontMotor);
	
<<<<<<< HEAD
	driveTrainLeftRearMotor = new Talon(1);
	lw->AddActuator("DriveTrain", "LeftRearMotor", (Talon*) driveTrainLeftRearMotor);
	
	driveTrainRightFrontMotor = new Talon(2);
	lw->AddActuator("DriveTrain", "RightFrontMotor", (Talon*) driveTrainRightFrontMotor);
	
	driveTrainRightRearMotor = new Talon(3);
	lw->AddActuator("DriveTrain", "RightRearMotor", (Talon*) driveTrainRightRearMotor);
	
	driveTrainMotorController = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRightRearMotor);
	
	driveTrainMotorController->SetSafetyEnabled(true);
        driveTrainMotorController->SetExpiration(0.1);
        driveTrainMotorController->SetSensitivity(0.5);
        driveTrainMotorController->SetMaxOutput(1.0);

        driveTrainMotorController->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        driveTrainMotorController->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
=======
	driveTrainLeftRearMotor = new TalonSRX(1);
	lw->AddActuator("DriveTrain", "LeftRearMotor", (TalonSRX*) driveTrainLeftRearMotor);
	
	driveTrainRightFrontMotor = new TalonSRX(2);
	lw->AddActuator("DriveTrain", "RightFrontMotor", (TalonSRX*) driveTrainRightFrontMotor);
	
	driveTrainRightRearMotor = new TalonSRX(3);
	lw->AddActuator("DriveTrain", "RightRearMotor", (TalonSRX*) driveTrainRightRearMotor);
	
	driveTrainRobotDrive4Motors = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRightRearMotor);
	
	driveTrainRobotDrive4Motors->SetSafetyEnabled(true);
        driveTrainRobotDrive4Motors->SetExpiration(0.1);
        driveTrainRobotDrive4Motors->SetSensitivity(0.5);
        driveTrainRobotDrive4Motors->SetMaxOutput(1.0);

        driveTrainRobotDrive4Motors->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        driveTrainRobotDrive4Motors->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
>>>>>>> origin/bailey
	driveTrainLeftFrontEncoder = new Encoder(0, 1, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "LeftFrontEncoder", driveTrainLeftFrontEncoder);
	driveTrainLeftFrontEncoder->SetDistancePerPulse(1.0);
        driveTrainLeftFrontEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainLeftRearEncoder = new Encoder(2, 3, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "LeftRearEncoder", driveTrainLeftRearEncoder);
	driveTrainLeftRearEncoder->SetDistancePerPulse(1.0);
        driveTrainLeftRearEncoder->SetPIDSourceParameter(Encoder::kRate);
<<<<<<< HEAD
	driveTrainRightFrontEncoder = new Encoder(4, 5, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightFrontEncoder", driveTrainRightFrontEncoder);
	driveTrainRightFrontEncoder->SetDistancePerPulse(1.0);
        driveTrainRightFrontEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainRightRearEncoder = new Encoder(6, 7, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightRearEncoder", driveTrainRightRearEncoder);
	driveTrainRightRearEncoder->SetDistancePerPulse(1.0);
        driveTrainRightRearEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainMainGyro = new Gyro(0);
	lw->AddSensor("DriveTrain", "MainGyro", driveTrainMainGyro);
	driveTrainMainGyro->SetSensitivity(0.007);
=======
	driveTrainRightFrontEncoder = new Encoder(4, 5, true, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightFrontEncoder", driveTrainRightFrontEncoder);
	driveTrainRightFrontEncoder->SetDistancePerPulse(1.0);
        driveTrainRightFrontEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainRightRearEncoder = new Encoder(6, 7, true, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightRearEncoder", driveTrainRightRearEncoder);
	driveTrainRightRearEncoder->SetDistancePerPulse(1.0);
        driveTrainRightRearEncoder->SetPIDSourceParameter(Encoder::kRate);
	driveTrainDriveGyro = new Gyro(0);
	lw->AddSensor("DriveTrain", "DriveGyro", driveTrainDriveGyro);
	driveTrainDriveGyro->SetSensitivity(0.007);
>>>>>>> origin/bailey


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
